package com.aiotouch.emojiquizapp;

import com.aiotouch.emojiquizapp.views.WelcomeScreen;
import com.codename1.admob.AdMobManager;
import com.codename1.components.ToastBar;
import com.codename1.system.Lifecycle;
import org.littlemonkey.connectivity.Connectivity;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class EmojiQuizApp extends Lifecycle {
    @Override
    public void runApp() {

        AdMobManager admob = null;

        /* CHECK USER'S NETWORK */
        if (Connectivity.isConnected()) {
            admob = new AdmobInit().admob;
            admob.loadAd();
        } else {
            ToastBar.Status noInternet = ToastBar.showErrorMessage("No Internet Connection!", 5000);
        }

        WelcomeScreen welcomeScreen = new WelcomeScreen();
        welcomeScreen.show();

        if (Connectivity.isConnected()) {
            admob.showAdIfLoaded();
        }
    }

}
