package com.aiotouch.emojiquizapp;

import static com.codename1.ui.CN.*;

import com.aiotouch.emojiquizapp.views.*;
import com.codename1.system.Lifecycle;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class EmojiQuizApp extends Lifecycle {
    @Override
    public void runApp() {
//        WelcomeScreen welcomeScreen = new WelcomeScreen();
//        welcomeScreen.show();

//        HowToPlayScreen hwtps = new HowToPlayScreen();
//        hwtps.show();

        QuestionScreen qs = new QuestionScreen();
        qs.show();
    }

}
